version: "3.8"

x-environment: &CLIENTBOTTLE_ENV
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example}
  POSTGRES_DB: ${POSTGRES_DB:-clientbottle}
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  MODE: ${MODE:-LOCAL}
  VERSION: ${VERSION:-0.0.1}
  AUTH_API_ORIGIN: ${AUTH_API_ORIGIN:-http://172.17.0.1:7071}

  SECRET_KEY: ${SECRET_KEY:-empty}
  ALGORITHM: ${ALGORITHM:-HS256}

  SMTP_USER: ${SMTP_USER:-clientbottle.noreply@gmail.com}
  SMTP_PASSWORD: ${SMTP_PASSWORD:-}
  SMTP_HOST: ${SMTP_HOST:-smtp4dev}
  SMTP_PORT: ${SMTP_PORT:-25}

  FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}

  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}

x-clientbottle-service: &CLIENTBOTTLE_SERVICE
  build:
    context: .
    args:
      VERSION: ${VERSION}
      ALGORITHM: ${ALGORITHM}
  restart: always
  depends_on:
    - postgres
  volumes:
    - ./server:/app/server
    - ./alembic:/app/alembic
    - ./alembic.ini:/app/alembic.ini
    - ./exec:/app/exec
    - ./.tmp/volumes/tmp:/app/.tmp
  networks:
    - internal

services:
  postgres:
    ports:
      - "5531:5432"
    image: postgres:16.1
    restart: always
    volumes:
      - ./.tmp/volumes/pg:/var/lib/postgresql/data
    environment: *CLIENTBOTTLE_ENV
    networks:
      - internal

  api:
    ports:
      - "7071:7071"
    image: thbraum/clientbottle:${VERSION}
    <<: *CLIENTBOTTLE_SERVICE
    environment:
      <<: *CLIENTBOTTLE_ENV

  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - "7073:80"
    networks:
      - internal

networks:
  internal:
    # external: true
