"""update current_timestamp_brazil default

Revision ID: f5058c00fe1a
Revises: c9a3252600bb
Create Date: 2024-08-04 19:13:56.535063

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5058c00fe1a"
down_revision: Union[str, None] = "c9a3252600bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
