"""user_token table

Revision ID: dc7000d3f930
Revises: 002860eaf021
Create Date: 2024-06-29 03:25:24.933195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc7000d3f930"
down_revision: Union[str, None] = "002860eaf021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_token",
        sa.Column("id_user_token", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fl_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("current_timestamp_brazil()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creation_user_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("update_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creation_user_id"],
            ["user.id_user"],
            name=op.f("fk_user_token_creation_user_id_user"),
        ),
        sa.ForeignKeyConstraint(
            ["id_user"], ["user.id_user"], name=op.f("fk_user_token_id_user_user")
        ),
        sa.ForeignKeyConstraint(
            ["update_user_id"], ["user.id_user"], name=op.f("fk_user_token_update_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id_user_token", name=op.f("pk_user_token")),
        sa.UniqueConstraint("api_key", name=op.f("uq_user_token_api_key")),
    )
    op.create_index(
        op.f("ix_user_token_creation_user_id"), "user_token", ["creation_user_id"], unique=False
    )
    op.create_index(op.f("ix_user_token_id_user"), "user_token", ["id_user"], unique=False)
    op.create_index(
        op.f("ix_user_token_update_user_id"), "user_token", ["update_user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_token_update_user_id"), table_name="user_token")
    op.drop_index(op.f("ix_user_token_id_user"), table_name="user_token")
    op.drop_index(op.f("ix_user_token_creation_user_id"), table_name="user_token")
    op.drop_table("user_token")
    # ### end Alembic commands ###
