"""add invite table

Revision ID: 9e41d799f14a
Revises: 002860eaf021
Create Date: 2024-07-28 20:57:56.510084

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e41d799f14a"
down_revision: Union[str, None] = "002860eaf021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite",
        sa.Column("id_invite", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.Enum("ADMINISTRATOR", "USER", name="userrole"), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("fl_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("current_timestamp_brazil()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creation_user_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("update_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creation_user_id"], ["user.id_user"], name=op.f("fk_invite_creation_user_id_user")
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["user.id_user"], name=op.f("fk_invite_sender_id_user")
        ),
        sa.ForeignKeyConstraint(
            ["update_user_id"], ["user.id_user"], name=op.f("fk_invite_update_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id_invite", name=op.f("pk_invite")),
        sa.UniqueConstraint("email", name=op.f("uq_invite_email")),
    )
    op.create_index(
        op.f("ix_invite_creation_user_id"), "invite", ["creation_user_id"], unique=False
    )
    op.create_index(op.f("ix_invite_sender_id"), "invite", ["sender_id"], unique=False)
    op.create_index(op.f("ix_invite_token"), "invite", ["token"], unique=True)
    op.create_index(op.f("ix_invite_update_user_id"), "invite", ["update_user_id"], unique=False)
    op.add_column(
        "user",
        sa.Column("role", sa.Enum("ADMINISTRATOR", "USER", name="userrole"), nullable=False),
    )
    op.drop_column("user", "api_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("api_key", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("user", "role")
    op.drop_index(op.f("ix_invite_update_user_id"), table_name="invite")
    op.drop_index(op.f("ix_invite_token"), table_name="invite")
    op.drop_index(op.f("ix_invite_sender_id"), table_name="invite")
    op.drop_index(op.f("ix_invite_creation_user_id"), table_name="invite")
    op.drop_table("invite")
    # ### end Alembic commands ###
