"""update client_bottle_transaction

Revision ID: a5b3d34b5fde
Revises: 933fc3a811b3
Create Date: 2024-08-19 01:07:39.745887

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5b3d34b5fde"
down_revision: Union[str, None] = "933fc3a811b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_bottle_id_bottle_brand"), "bottle", ["id_bottle_brand"], unique=False)
    op.add_column(
        "client_bottle_transaction",
        sa.Column(
            "transaction_data_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    op.alter_column(
        "client_bottle_transaction",
        "transaction_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        existing_nullable=False,
        existing_server_default=sa.text("current_timestamp_brazil()"),
    )
    op.drop_index("ClientBotteTransaction_UNIQUE", table_name="client_bottle_transaction")
    op.create_index(
        "idx_transaction_data_json",
        "client_bottle_transaction",
        ["transaction_data_json"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_transaction_date", "client_bottle_transaction", ["transaction_date"], unique=False
    )
    op.drop_constraint(
        "fk_client_bottle_transaction_id_bottle_bottle",
        "client_bottle_transaction",
        type_="foreignkey",
    )
    op.drop_column("client_bottle_transaction", "id_bottle")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_bottle_transaction",
        sa.Column("id_bottle", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_client_bottle_transaction_id_bottle_bottle",
        "client_bottle_transaction",
        "bottle",
        ["id_bottle"],
        ["id_bottle"],
    )
    op.drop_index("idx_transaction_date", table_name="client_bottle_transaction")
    op.drop_index(
        "idx_transaction_data_json", table_name="client_bottle_transaction", postgresql_using="gin"
    )
    op.create_index(
        "ClientBotteTransaction_UNIQUE",
        "client_bottle_transaction",
        ["id_client", "id_bottle", "fl_active"],
        unique=True,
    )
    op.alter_column(
        "client_bottle_transaction",
        "transaction_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("current_timestamp_brazil()"),
    )
    op.drop_column("client_bottle_transaction", "transaction_data_json")
    op.drop_index(op.f("ix_bottle_id_bottle_brand"), table_name="bottle")
    # ### end Alembic commands ###
